version: "3.9"  # optional since v1.27.0
services:
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: development
      MONGO_DB_CONNECTION_STRING: mongodb+srv://admin:4k1M80XOPn1Mprlf@gcp-sem9.7obik0r.mongodb.net/?retryWrites=true&w=majority
      MONGO_DB_NAME: GCP-SEM9
      REDIS_URI: redisDB
    depends_on:
      - redisDB
  redisDB:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server